#!/bin/bash

FPK=`cat ~/chia-scripts/config.txt | grep -v '#' | sed "s/ //g;s/'//g;s/\"//g" | grep fpk | sed "s/fpk=//"`
echo "Farmer Publc Key = $FPK"

NFT=`cat ~/chia-scripts/config.txt | grep -v '#' | sed "s/ //g;s/'//g;s/\"//g" | grep nft | sed "s/nft=//"`
echo "Pool Contract Address = $NFT"

USER=`cat ~/chia-scripts/config.txt | grep -v '#' | sed "s/ //g;s/'//g;s/\"//g" | grep user | sed "s/user=//"`
echo "Chia user = $USER"

TEMP=`cat ~/chia-scripts/config.txt | grep -v '#' | sed -e "s/ //g;s/'//g;s/\"//g;s/.*\/$//" | grep temp | sed "s/temp=//"`
echo "Chia user tempdir = $TEMP"

RAM=`cat ~/chia-scripts/config.txt | grep -v '#' | sed -e "s/ //g;s/'//g;s/\"//g;s/.*\/$//" | grep ram | sed "s/ram=//"`
echo "Chia user ramdir = $RAM"

FARM=`cat ~/chia-scripts/config.txt | grep -v '#' | sed -e "s/ //g;s/'//g;s/\"//g;s/.*\/$//" | grep farm | sed "s/farm=//"`
echo "Chia Farm dir = $FARM"

export CHIA_FPK=$FPK
export CHIA_NFT=$NFT
export CHIA_USER=$USER
export CHIA_TEMP=$TEMP
export CHIA_RAM=$RAM
export CHIA_FARM=$FARM