#!/bin/bash
MARKER='chia_mm'
FOUND=`screen -ls | grep $MARKER | wc -l`
CMD1='su - chia\n'
CMD2='~/chia-scripts/chia_mm.sh\n'
[[ $FOUND == "0" ]] && (screen -dmS $MARKER && screen -S $MARKER -X stuff "$CMD1" && screen -S $MARKER -X stuff "$CMD2" && screen -x $MARKER) ||  screen -x $MARKER
