#!/bin/bash
MARKER='chia_log'
FOUND=`screen -ls | grep $MARKER | wc -l`
CMD1='su - chia\n'
CMD2='/home/chia/chia_log.sh\n'
[[ $FOUND == "0" ]] && (screen -dmS $MARKER && screen -S $MARKER -X stuff "$CMD1" && screen -S $MARKER -X stuff "$CMD2" && screen -x $MARKER) ||  screen -x $MARKER


